# fly.toml app configuration file generated for eventlite-annewil on 2023-09-12T10:00:24-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eventlite-annewil"
primary_region = "iad"

[env]
AWS_BUCKET = "eventlite-annewil-uploads"
PORT = "3000"
RAILS_LOG_TO_STDOUT = "1"
RAILS_SERVE_STATIC_FILES = "1"
SITE_DOMAIN = "larp.annewil.com"

[deploy]
release_command = "bundle exec rake db:migrate"
strategy = "rolling"

[build]
image = "ghcr.io/nbudin/eventlite"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3000
min_machines_running = 0
