default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  user: postgres

development:
  <<: *default
  database: eventlite_development

test:
  <<: *default
  database: eventlite_test
